server:
  port: 8081

okta-url: https://dev-275566.okta.com
azure-tenant-id: a805eb36-3833-4902-88c2-5cb74b2cbcbf
azure-nbc-tenant-id: a927fef0-4195-40ae-8c0e-ebcb64c9a765

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    io.fdlessard.codebites.oauth2.sso.apps.api1: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
## For azure the issuer-uri work only if "accessTokenAcceptedVersion": 2 in the manifest. If not, use jwk-set-uri
          issuer-uri: https://login.microsoftonline.com/0e9e4220-9d42-4d1d-ab6e-9448586cc572/v2.0
#          issuer-uri: https://login.microsoftonline.com/${azure-nbc-tenant-id}/v2.0
##          jwk-set-uri: https://login.microsoftonline.com/${azure-tenant-id}/discovery/v2.0/keys
#          issuer-uri: ${okta-url}/oauth2/default






