server:
  port: 8081

logging:
  level.io.fdlessard.codebites.oauth2.sso.apps.api1: DEBUG
#  level.root: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-275566.okta.com/oauth2/default/v1/keys

