server:
  port: 8080

okta-url: https://dev-275566.okta.com
okta-client-id: 0oa2a55teeqhX2CcY4x6
okta-client-secret: HvpaK1PR-wWm6dzioLSjXFKMVkNiz6-emo7YHc6A

azure-tenant-id: a805eb36-3833-4902-88c2-5cb74b2cbcbf
azure-client-id: b19a6e57-ea73-49f9-9a00-37a76b8781ef
azure-client-secret: 2Mdp73zxsRQ/?wjOmos:zi3qGsT?=d2U

logging:
  level:
    root: DEBUG
    io.fdlessard.codebites.oauth2.sso.apps.ui: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          ui-login:
            client-name: Azure
            provider: azure
            client-id: ${azure-client-id}
            client-secret: ${azure-client-secret}
###            client-authentication-method: none
###            authorization-grant-type: authorization_code
            scope: openid, profile, email, api://b19a6e57-ea73-49f9-9a00-37a76b8781ef/fdlessard.Read
            redirect-uri: http://localhost:8080/login/oauth2/code/azure
#            client-name: Okta
#            provider: okta
#            client-id: ${okta-client-id}
#            client-secret:  ${okta-client-secret}
#            redirect-uri: http://localhost:8080/login/oauth2/code/okta
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${azure-tenant-id}/v2.0
## The following are not needed if you provide issuer-uri
#            authorization-uri: https://login.microsoftonline.com/${azure-tenant-id}/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/${azure-tenant-id}/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            user-name-attribute: sub
#            jwk-set-uri: https://login.microsoftonline.com/${azure-tenant-id}/discovery/v2.0/keys
          okta:
            issuer-uri: ${okta-url}/oauth2/default