server:
  port: 8080

management:
  trace:
    http:
      enabled: true
      include: request-headers,response-headers,cookies,errors,parameters

logging:
  level.io.fdlessard.codebites.oauth2.sso.apps.ui: DEBUG
  level.org.springframework.web.client.RestTemplate: DEBUG
  level.org.apache.http: DEBUG
  level.org.apache.http.wire: DEBUG
  level.root: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-name: Okta
            client-id: 0oa2a55teeqhX2CcY4x6
            client-secret: HvpaK1PR-wWm6dzioLSjXFKMVkNiz6-emo7YHc6A
          azure:
            client-id: b19a6e57-ea73-49f9-9a00-37a76b8781ef
            client-secret: 2Mdp73zxsRQ/?wjOmos:zi3qGsT?=d2U
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/azure
        provider:
          okta:
            issuer-uri: https://dev-275566.okta.com/oauth2/default
          azure:
            issuer-uri: https://login.microsoftonline.com/a805eb36-3833-4902-88c2-5cb74b2cbcbf/oauth2/default

azure:
  activedirectory:
    tenant-id: a805eb36-3833-4902-88c2-5cb74b2cbcbf
    active-directory-groups: group1, group2

