server:
  port: 8080

# Okta
okta-url: https://dev-275566.okta.com
okta-ui-login-client-id: 0oa2a55teeqhX2CcY4x6
okta-ui-login-client-secret: T3uK[4iCM_2wvC@.aNSXiO9:4oN8ybCO
okta-api1-client-id: 0oa30501tpULFXzK64x6
okta-api1-client-secret: ImoEqh8DHq0FMij8OrLIKKUa9nbKkFrsnGRAEHNV
okta-api2-client-id: 0oa320swcyBDv8VbR4x6
okta-api2-client-secret: MKQTKEOiJ6V0VqhOpPUatKohuzlNGKwh-GQRMUl4

# Personal Azure Active Directory Service
azure-fdl-tenant-id: a805eb36-3833-4902-88c2-5cb74b2cbcbf
azure-fdl-ui-login-client-id: b19a6e57-ea73-49f9-9a00-37a76b8781ef
azure-fdl-ui-login-client-secret: ODnRXZYNEevlu?Ae5eRqw.M0Vvis]9?7

azure-fdl-api1-client-id: 3025d3c1-8fde-4fce-a04d-5baf4f1f9685
azure-fdl-api1-client-secret: sx:BDo]NxL?jCmuArprZ8inb3Yb.vx51

azure-fdl-api2-client-id: acf35bd0-20f8-4f3d-82b9-ba68b59616fe
azure-fdl-api2-client-secret: W:@0z0WI/AfD?LSEXsw8YjaKlM1MKIW?

logging:
  level:
    root: DEBUG
    io.fdlessard.codebites.oauth2.sso.apps.ui: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          ui-login:
            client-name: UI Login
#            provider: okta
#            client-id: ${okta-ui-login-client-id}
#            client-secret: ${okta-ui-login-client-secret}
#            client-authentication-method: none
#            authorization-grant-type: authorization_code
## The api://b19a6e57-ea73-49f9-9a00-37a76b8781ef/fdlessard.Read scope is needed to prevent adding a nounce
## in Azure Microsoft Active Directory (see README file)
            provider: azure
            client-id: ${azure-fdl-ui-login-client-id}
            client-secret: ${azure-fdl-ui-login-client-secret}
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorization-grant-type: authorization_code
#            scope: openid,profile,email,api://40ce5a52-6aa3-4d05-824d-5f74c6076010/FMCRM.Read
            scope: openid,profile,email
#            authorization-grant-type: authorization_code
#            client-authentication-method: none
          api-1:
            client-name: API 1
            provider: azure
            authorization-grant-type: client_credentials
            redirect-uri: "{baseUrl}/api1"
            client-id: ${azure-fdl-api1-client-id}
            client-secret: ${azure-fdl-api1-client-secret}
            scope: 'api://3025d3c1-8fde-4fce-a04d-5baf4f1f9685/.default'
#            provider: okta
#            client-id: ${okta-api1-client-id}
#            client-secret: ${okta-api1-client-secret}
#            scope: authority-api1
          api-2:
            client-name:  API 2
            provider: azure
            authorization-grant-type: client_credentials
            redirect-uri: "{baseUrl}/api2"
            client-id: ${azure-fdl-api2-client-id}
            client-secret: ${azure-fdl-api2-client-secret}
            scope: 'api://acf35bd0-20f8-4f3d-82b9-ba68b59616fe/.default'
#            provider: okta
#            client-id: ${okta-api2-client-id}
#            client-secret: ${okta-api2-client-secret}
#            redirect-uri: "{baseUrl}/api2"
#            scope: authority-api2
        provider:
          okta:
            issuer-uri: ${okta-url}/oauth2/default
          azure:
            issuer-uri: https://login.microsoftonline.com/${azure-fdl-tenant-id}/v2.0
## The following are not needed if you provide issuer-uri
#            authorization-uri: https://login.microsoftonline.com/${azure-tenant-id}/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/${azure-tenant-id}/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            user-name-attribute: sub
#            jwk-set-uri: https://login.microsoftonline.com/${azure-tenant-id}/discovery/v2.0/keys

# https://login.microsoftonline.com/a805eb36-3833-4902-88c2-5cb74b2cbcbf/v2.0/.well-known/openid-configuration