server:
  port: 8082

logging:
  level.io.fdlessard.codebites.oauth2.sso.apps.api2: DEBUG
#  level.root: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-275566.okta.com/oauth2/default/v1/keys

