server:
  port: 8082

logging:
  level.io.fdlessard.codebites.oauth2.sso.apps.api2: DEBUG
#    org.springframework.security: INFO
#    org.springframework.security.oauth2: INFO
#  level.root: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#         jwk-set-uri: https://dev-275566.okta.com/oauth2/default/v1/keys
          jwk-set-uri: https://login.microsoftonline.com/a805eb36-3833-4902-88c2-5cb74b2cbcbf/discovery/v2.0/keys


