server:
  port: 8082

okta-url: https://dev-275566.okta.com
azure-fdl-tenant-id: a805eb36-3833-4902-88c2-5cb74b2cbcbf

logging:
  level:
    root: DEBUG
    io.fdlessard.codebites.oauth2.sso.apps.api2: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
## For azure the issuer-uri work only if "accessTokenAcceptedVersion": 2 in the manifest. If not, use jwk-set-uri
          issuer-uri: https://login.microsoftonline.com/${azure-fdl-tenant-id}/v2.0
##          jwk-set-uri: https://login.microsoftonline.com/${azure-fdl-tenant-id}/discovery/v2.0/keys
#          issuer-uri: ${okta-url}/oauth2/default


